name: 'Publish application'
on: 
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: windows-latest
    
    env:
     PUBLISH_FOLDER: Blazor.Midi.GoKeys/bin/Release/net9.0/publish/wwwroot

    name: Build and Deploy Job
    steps:
      - name: Set the name of the repo in env variable 
        run: 
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Dotnet Build
        run: |
          dotnet build Blazor.Midi.GoKeys/Blazor.Midi.GoKeys.csproj --configuration Release

      - name: Dotnet Publish
        run: 
            dotnet publish --configuration Release

      - name: Change base-tag in index.html to repo name
        #run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html
        # Remplacez la ligne sed par cette Ã©tape PowerShell
        shell: pwsh
        run: |
          $indexPath = "$env:GITHUB_WORKSPACE/$env:PUBLISH_FOLDER/index.html"
          $repoName = "${{ env.REPO_NAME }}"
          $content = Get-Content $indexPath -Raw
          $content = $content -replace '<base href="/" />', "<base href=`"/$repoName/`" />"
          Set-Content $indexPath $content -NoNewline
  
      - name: copy index.html to 404.html
        #run: cp $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html $GITHUB_WORKSPACE/$PUBLISH_FOLDER/404.html
        shell: pwsh
        run: |
          $sourcePath = Join-Path $env:GITHUB_WORKSPACE $env:PUBLISH_FOLDER "index.html"
          $destPath = Join-Path $env:GITHUB_WORKSPACE $env:PUBLISH_FOLDER "404.html"
          Copy-Item $sourcePath $destPath
      
      - name: Add .nojekyll file
        run: touch $PUBLISH_FOLDER/.nojekyll
        
      - name: Deploy GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: /${{ env.PUBLISH_FOLDER }}
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
